# Generated by Django 3.2.13 on 2022-11-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_restaurant_wishlist'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wished_users', to='Restaurant.Restaurant'),
        ),
    ]
