# Generated by Django 3.2.13 on 2022-11-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_restaurant_wishlist'),
        ('users', '0003_remove_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_wishlist',
            field=models.ManyToManyField(related_name='user_wishlist', to='Restaurant.Restaurant'),
        ),
    ]
