# Generated by Django 3.2.13 on 2022-11-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hp',
            field=models.IntegerField(null=True, verbose_name='핸드폰번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=8, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=17, unique=True, verbose_name='아이디'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, null=True, verbose_name='이메일'),
        ),
    ]
