# Generated by Django 3.2.13 on 2022-11-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Restaurant_id',
            new_name='Restaurant',
        ),
    ]
