# Generated by Django 3.2.13 on 2022-11-03 08:28

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('addr', models.CharField(max_length=255)),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('tel', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('imgurl', models.TextField()),
            ],
        ),
    ]
