# Generated by Django 3.2.13 on 2022-11-02 13:14

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=64, verbose_name='전화')),
                ('category', models.CharField(choices=[('양식', '양식'), ('중식', '중식'), ('한식', '한식')], max_length=18, verbose_name='분류')),
                ('menu', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
