# Generated by Django 3.2.13 on 2022-11-04 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist_res', to=settings.AUTH_USER_MODEL),
        ),
    ]
