# Generated by Django 3.2.13 on 2022-11-03 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurant', '0002_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist_res', to=settings.AUTH_USER_MODEL),
        ),
    ]
